export const languageToCountry: Record<string, string> = {
  'zh-CN': '中国',
  'zh-TW': '中国',
  'en': 'United States',
  'ja': 'Japan',
  'fr': 'France',
  'de': 'Germany',
  'es': 'Spain',
  'ar': 'Egypt',
  'hi': 'India',
  'km': 'Cambodia',
  'ur': 'Pakistan',
  'el': 'Greece',
  'tr': 'Turkey',
  'ne': 'Nepal',
  'bs': 'Bosnia and Herzegovina',
  'sr': 'Serbia',
  'hr': 'Croatia',
  'ga': 'Ireland',
};

export const hotCitiesByCountry: Record<string, string[]> = {
  '中国': ['beijing', 'shanghai', 'guangzhou', 'shenzhen', 'chengdu', 'chongqing', 'hangzhou', 'xian'],
  'China': ['beijing', 'shanghai', 'guangzhou', 'shenzhen', 'chengdu', 'chongqing', 'hangzhou', 'xian'],
  'United States': ['newyork', 'losangeles', 'chicago', 'houston', 'phoenix', 'philadelphia', 'sanantonio', 'sandiego'],
  '美国': ['newyork', 'losangeles', 'chicago', 'houston', 'phoenix', 'philadelphia', 'sanantonio', 'sandiego'],
  'United Kingdom': ['london', 'manchester', 'birmingham', 'liverpool', 'leeds', 'glasgow', 'sheffield', 'bristol'],
  '英国': ['london', 'manchester', 'birmingham', 'liverpool', 'leeds', 'glasgow', 'sheffield', 'bristol'],
  'France': ['paris', 'marseille', 'lyon', 'toulouse', 'nice', 'nantes', 'strasbourg', 'montpellier'],
  '法国': ['paris', 'marseille', 'lyon', 'toulouse', 'nice', 'nantes', 'strasbourg', 'montpellier'],
  'Egypt': ['cairo', 'alexandria', 'giza', 'shubra', 'portsaid', 'suez', 'luxor', 'asyut'],
  '埃及': ['cairo', 'alexandria', 'giza', 'shubra', 'portsaid', 'suez', 'luxor', 'asyut'],
  'Saudi Arabia': ['riyadh', 'jeddah', 'mecca', 'medina', 'dammam', 'khobar', 'tabuk', 'abha'],
  '沙特阿拉伯': ['riyadh', 'jeddah', 'mecca', 'medina', 'dammam', 'khobar', 'tabuk', 'abha'],
  'India': ['delhi', 'mumbai', 'bangalore', 'kolkata', 'chennai', 'hyderabad', 'pune', 'ahmedabad'],
  '印度': ['delhi', 'mumbai', 'bangalore', 'kolkata', 'chennai', 'hyderabad', 'pune', 'ahmedabad'],
  'Cambodia': ['phnompenh', 'siemreap', 'battambang', 'sihanoukville', 'kampongcham', 'kampot', 'takhmau', 'poipet'],
  '柬埔寨': ['phnompenh', 'siemreap', 'battambang', 'sihanoukville', 'kampongcham', 'kampot', 'takhmau', 'poipet'],
  'Pakistan': ['karachi', 'lahore', 'faisalabad', 'rawalpindi', 'multan', 'hyderabadpk', 'gujranwala', 'peshawar'],
  '巴基斯坦': ['karachi', 'lahore', 'faisalabad', 'rawalpindi', 'multan', 'hyderabadpk', 'gujranwala', 'peshawar'],
  'Greece': ['athens', 'thessaloniki', 'patras', 'heraklion', 'larissa', 'volos', 'ioannina', 'chania'],
  '希腊': ['athens', 'thessaloniki', 'patras', 'heraklion', 'larissa', 'volos', 'ioannina', 'chania'],
  'Turkey': ['istanbul', 'ankara', 'izmir', 'bursa', 'adana', 'gaziantep', 'konya', 'antalya'],
  '土耳其': ['istanbul', 'ankara', 'izmir', 'bursa', 'adana', 'gaziantep', 'konya', 'antalya'],
  'Nepal': ['kathmandu', 'pokhara', 'lalitpur', 'bharatpur', 'biratnagar', 'birgunj', 'dharan', 'bhaktapur'],
  '尼泊尔': ['kathmandu', 'pokhara', 'lalitpur', 'bharatpur', 'biratnagar', 'birgunj', 'dharan', 'bhaktapur'],
  'Bosnia and Herzegovina': ['sarajevo', 'banjaluka', 'tuzla', 'zenica', 'mostar', 'bijeljina', 'prijedor', 'brcko'],
  '波黑': ['sarajevo', 'banjaluka', 'tuzla', 'zenica', 'mostar', 'bijeljina', 'prijedor', 'brcko'],
  'Serbia': ['belgrade', 'novisad', 'nis', 'kragujevac', 'subotica', 'zrenjanin', 'pancevo', 'cacak'],
  '塞尔维亚': ['belgrade', 'novisad', 'nis', 'kragujevac', 'subotica', 'zrenjanin', 'pancevo', 'cacak'],
  'Croatia': ['zagreb', 'split', 'rijeka', 'osijek', 'zadar', 'slavonskibrod', 'pula', 'karlovac'],
  '克罗地亚': ['zagreb', 'split', 'rijeka', 'osijek', 'zadar', 'slavonskibrod', 'pula', 'karlovac'],
  'Ireland': ['dublin', 'cork', 'limerick', 'galway', 'waterford', 'drogheda', 'dundalk', 'swords'],
  '爱尔兰': ['dublin', 'cork', 'limerick', 'galway', 'waterford', 'drogheda', 'dundalk', 'swords'],
  'Japan': ['tokyo', 'osaka', 'yokohama', 'nagoya', 'sapporo', 'fukuoka', 'kobe', 'kyoto'],
  '日本': ['tokyo', 'osaka', 'yokohama', 'nagoya', 'sapporo', 'fukuoka', 'kobe', 'kyoto'],
  'Germany': ['berlin', 'hamburg', 'munich', 'cologne', 'frankfurt', 'stuttgart', 'dusseldorf', 'dortmund'],
  '德国': ['berlin', 'hamburg', 'munich', 'cologne', 'frankfurt', 'stuttgart', 'dusseldorf', 'dortmund'],
  'Spain': ['madrid', 'barcelona', 'valencia', 'seville', 'zaragoza', 'malaga', 'murcia', 'palma'],
  '西班牙': ['madrid', 'barcelona', 'valencia', 'seville', 'zaragoza', 'malaga', 'murcia', 'palma'],
}; 